name: MentionChat
version: '${project.version}'
description: A simple plugin to mention other players in chat!
author: JovannMC
main: me.jovannmc.mentionchat.MentionChat
api-version: 1.13
commands:
  mentionchat:
    description: MentionChat's main command. Use /mentionchat help for more info.
    aliases: [mc]
permissions:
  mentionchat.*:
    description: Gives access to all of MentionChat's permissions and commands (except for mentionchat.mention.exempt).
    children:
      mentionchat.command.info: true
      mentionchat.command.reload: true
      mentionchat.command.help: true
      mentionchat.command.settings: true
      mentionchat.command.settings.toggle: true
      mentionchat.command.settings.format: true
      mentionchat.command.settings.sound: true
      mentionchat.mention.others: true
      mentionchat.mention.everyone: true
      mentionchat.mention.bypass: true
  mentionchat.command.info:
    description: Allows players to view MentionChat's info and perform an update check.
    default: true
  mentionchat.command.reload:
    description: Allows players to reload MentionChat's config.
    default: OP
  mentionchat.command.help:
    description: Allows players to view MentionChat's help page.
    default: true
  mentionchat.command.settings:
    description: Allows players to modify their settings for MentionChat.
    default: true
  mentionchat.command.settings.toggle:
    description: Allows players to toggle their mentions on and off.
    default: true
  mentionchat.command.settings.format:
    description: Allows players to change their mention format.
    default: true
  mentionchat.command.settings.sound:
    description: Allows players to change their mention sound.
    default: true
  mentionchat.mention.others:
    description: Allows players to mention other players in chat.
    default: true
  mentionchat.mention.everyone:
    description: Allows players to mention everyone in chat.
    default: OP
  mentionchat.mention.bypass:
    description: Allows players to bypass the cooldown between mentions, mention toggles and exempt permission node.
    default: OP
  mentionchat.mention.bypass.cooldown:
    description: Allows players to bypass the cooldown between mentions.
    default: OP
  mentionchat.mention.bypass.toggle:
    description: Allows players to bypass the mention toggle.
    default: OP
  mentionchat.mention.bypass.exempt:
    description: Allows players to bypass the mention exemption permission node.
    default: OP
  mentionchat.mention.exempt:
    description: Allows players to be exempt from being mentioned, no matter their mention toggle.
    default: false